"""Paper attempts repository.

Manages paper_attempts table, which tracks each sitting of a paper by a student.

Design:
- Each attempt has both id (internal) and attempt_uuid (external)
- UUID generated by caller (CLI/frontend), not repository
- Status derived from timestamps (submitted_at, completed_at)
- Soft delete via deleted_at timestamp (preserves audit trail)
- Inheritance tracked via inherited_from_attempt

Usage:
    # CLI layer opens connection and manages transaction
    from paperlab.data.repositories.marking import paper_attempts
    from paperlab.data.database import connection
    import uuid

    with connection() as conn:
        attempt = paper_attempts.create_attempt(
            attempt_uuid=str(uuid.uuid4()),
            student_id=1,
            paper_id=1,
            inherited_from_attempt=None,
            conn=conn
        )
        conn.commit()  # CLI layer commits
"""

from sqlite3 import Connection
from typing import Any

from paperlab.config.constants import Tables
from paperlab.data.models.marking import PaperAttempt


def create_attempt(
    attempt_uuid: str,
    student_id: int,
    paper_id: int,
    inherited_from_attempt: int | None,
    conn: Connection,
) -> PaperAttempt:
    """Create new paper attempt with caller-provided UUID.

    Args:
        attempt_uuid: UUID for this paper attempt (generated by caller)
        student_id: Student creating the attempt
        paper_id: Paper being attempted
        inherited_from_attempt: Optional previous attempt ID to inherit from
                               (must reference a completed attempt)
        conn: Database connection

    Returns:
        PaperAttempt with both id and attempt_uuid populated

    Raises:
        ValueError: If inheriting from incomplete attempt or if student has
                   existing in-progress attempt

    Note:
        UUID is generated by caller (CLI or frontend), not repository.
        This enables idempotent operations and frontend control.
        M4: CLI generates UUID in command layer
        M5: Frontend generates UUID before API call
    """
    # Validate inheritance (if provided)
    if inherited_from_attempt is not None:
        previous = get_attempt(inherited_from_attempt, conn)
        if previous.completed_at is None:
            raise ValueError(f"Cannot inherit from incomplete attempt {inherited_from_attempt}")

        # CRITICAL: Prevent cross-student inheritance (academic dishonesty)
        if previous.student_id != student_id:
            raise ValueError(
                f"Cannot inherit from another student's attempt "
                f"(attempt {inherited_from_attempt} belongs to student {previous.student_id})"
            )

        # Check for existing incomplete retry attempts (prevent concurrent retries)
        existing_retry = conn.execute(
            f"""
            SELECT id FROM {Tables.PAPER_ATTEMPTS}
            WHERE student_id = ?
              AND paper_id = ?
              AND completed_at IS NULL
              AND deleted_at IS NULL
        """,
            (student_id, paper_id),
        ).fetchone()

        if existing_retry:
            raise ValueError(
                f"You already have an in-progress attempt (ID: {existing_retry[0]}). "
                "Please complete or delete it before creating a new retry."
            )

    # Insert attempt with caller-provided UUID
    cursor = conn.execute(
        f"""
        INSERT INTO {Tables.PAPER_ATTEMPTS}
        (attempt_uuid, student_id, paper_id, inherited_from_attempt)
        VALUES (?, ?, ?, ?)
    """,
        (attempt_uuid, student_id, paper_id, inherited_from_attempt),
    )

    attempt_id = cursor.lastrowid
    if attempt_id is None:
        raise ValueError("Failed to get attempt_id after INSERT")

    return get_attempt(attempt_id, conn)


def get_attempt_by_uuid(attempt_uuid: str, conn: Connection) -> PaperAttempt | None:
    """Get paper attempt by UUID.

    Args:
        attempt_uuid: External UUID
        conn: Database connection

    Returns:
        PaperAttempt record if found, None otherwise
    """
    cursor = conn.execute(
        f"""
        SELECT id, attempt_uuid, student_id, paper_id, inherited_from_attempt,
               submitted_at, completed_at, deleted_at, deleted_by, created_at
        FROM {Tables.PAPER_ATTEMPTS}
        WHERE attempt_uuid = ?
    """,
        (attempt_uuid,),
    )

    row = cursor.fetchone()
    if row is None:
        return None

    return PaperAttempt(
        id=row[0],
        attempt_uuid=row[1],
        student_id=row[2],
        paper_id=row[3],
        inherited_from_attempt=row[4],
        submitted_at=row[5],
        completed_at=row[6],
        deleted_at=row[7],
        deleted_by=row[8],
        created_at=row[9],
    )


def get_attempt(attempt_id: int, conn: Connection) -> PaperAttempt:
    """Get paper attempt by internal ID.

    Args:
        attempt_id: Database ID
        conn: Database connection

    Returns:
        PaperAttempt record

    Raises:
        ValueError: If attempt not found
    """
    cursor = conn.execute(
        f"""
        SELECT id, attempt_uuid, student_id, paper_id, inherited_from_attempt,
               submitted_at, completed_at, deleted_at, deleted_by, created_at
        FROM {Tables.PAPER_ATTEMPTS}
        WHERE id = ?
    """,
        (attempt_id,),
    )

    row = cursor.fetchone()
    if row is None:
        raise ValueError(f"Paper attempt {attempt_id} not found")

    return PaperAttempt(
        id=row[0],
        attempt_uuid=row[1],
        student_id=row[2],
        paper_id=row[3],
        inherited_from_attempt=row[4],
        submitted_at=row[5],
        completed_at=row[6],
        deleted_at=row[7],
        deleted_by=row[8],
        created_at=row[9],
    )


def get_attempts_for_student(student_id: int, conn: Connection) -> list[dict[str, Any]]:
    """Get all paper attempts for student with paper names.

    Returns attempts with paper display names from joined tables.
    Excludes soft-deleted attempts (deleted_at IS NULL).
    Orders by most recent first.

    Args:
        student_id: Student ID
        conn: Database connection

    Returns:
        List of dicts with keys:
        - id: int
        - attempt_uuid: str
        - paper_name: str (from papers.display_name)
        - exam_date: str (from papers.exam_date)
        - created_at: datetime
        - submitted_at: datetime | None
        - completed_at: datetime | None
        - grade: int | None (from paper_results.indicative_grade)

    Example:
        >>> attempts = get_attempts_for_student(1, conn)
        >>> attempts[0]["paper_name"]
        "1MA1 Paper 3 Higher Nov 2023"
    """
    cursor = conn.execute(
        f"""
        SELECT
            pa.id,
            pa.attempt_uuid,
            COALESCE(et.display_name, p.exam_identifier) as paper_name,
            p.exam_date,
            pa.created_at,
            pa.submitted_at,
            pa.completed_at,
            pr.indicative_grade as grade
        FROM {Tables.PAPER_ATTEMPTS} pa
        JOIN {Tables.PAPERS} p ON pa.paper_id = p.id
        LEFT JOIN {Tables.EXAM_TYPES} et ON p.exam_type_id = et.id
        LEFT JOIN {Tables.PAPER_RESULTS} pr ON pa.id = pr.paper_attempt_id
        WHERE pa.student_id = ?
          AND pa.deleted_at IS NULL
        ORDER BY pa.created_at DESC
    """,
        (student_id,),
    )

    columns = [
        "id",
        "attempt_uuid",
        "paper_name",
        "exam_date",
        "created_at",
        "submitted_at",
        "completed_at",
        "grade",
    ]
    return [dict(zip(columns, row, strict=False)) for row in cursor.fetchall()]


def mark_as_submitted(attempt_id: int, conn: Connection) -> None:
    """Set submitted_at to NOW().

    Args:
        attempt_id: Paper attempt ID
        conn: Database connection
    """
    conn.execute(
        f"""
        UPDATE {Tables.PAPER_ATTEMPTS}
        SET submitted_at = CURRENT_TIMESTAMP
        WHERE id = ?
    """,
        (attempt_id,),
    )


def mark_as_complete(attempt_id: int, conn: Connection) -> None:
    """Set completed_at to NOW().

    Args:
        attempt_id: Paper attempt ID
        conn: Database connection
    """
    conn.execute(
        f"""
        UPDATE {Tables.PAPER_ATTEMPTS}
        SET completed_at = CURRENT_TIMESTAMP
        WHERE id = ?
    """,
        (attempt_id,),
    )


def soft_delete_attempt(
    paper_attempt_id: int,
    deleted_by: int,
    conn: Connection,
) -> None:
    """Soft delete paper attempt (hide from UI, preserve audit trail).

    Sets deleted_at timestamp. Data preserved for:
    - Cost tracking (LLM spend)
    - Analytics (improvement tracking)
    - Audit trail (compliance)
    - Admin review

    Args:
        paper_attempt_id: Paper attempt ID to delete
        deleted_by: Student ID who deleted it
        conn: Database connection

    Raises:
        ValueError: If attempt doesn't exist or already deleted
    """
    # Check if exists and not already deleted
    cursor = conn.execute(
        f"SELECT id FROM {Tables.PAPER_ATTEMPTS} " f"WHERE id = ? AND deleted_at IS NULL",
        (paper_attempt_id,),
    )
    if cursor.fetchone() is None:
        raise ValueError(f"Paper attempt {paper_attempt_id} not found or already deleted")

    # Soft delete
    conn.execute(
        f"""
        UPDATE {Tables.PAPER_ATTEMPTS}
        SET deleted_at = CURRENT_TIMESTAMP,
            deleted_by = ?
        WHERE id = ?
    """,
        (deleted_by, paper_attempt_id),
    )


def restore_attempt(
    paper_attempt_id: int,
    restored_by: int,
    conn: Connection,
) -> None:
    """Restore soft-deleted paper attempt.

    Clears deleted_at timestamp to make attempt visible again.
    Used for undo functionality after accidental delete.

    Args:
        paper_attempt_id: Paper attempt ID to restore
        restored_by: Student ID who is restoring it
        conn: Database connection

    Raises:
        ValueError: If attempt doesn't exist, not deleted, or not owned by student
    """
    # Check if exists and is deleted, and owned by the student
    cursor = conn.execute(
        f"""
        SELECT id, student_id FROM {Tables.PAPER_ATTEMPTS}
        WHERE id = ? AND deleted_at IS NOT NULL
        """,
        (paper_attempt_id,),
    )
    row = cursor.fetchone()
    if row is None:
        raise ValueError(f"Paper attempt {paper_attempt_id} not found or not deleted")

    if row[1] != restored_by:
        raise ValueError(f"Paper attempt {paper_attempt_id} not owned by student {restored_by}")

    # Restore (clear deleted_at and deleted_by)
    conn.execute(
        f"""
        UPDATE {Tables.PAPER_ATTEMPTS}
        SET deleted_at = NULL,
            deleted_by = NULL
        WHERE id = ?
        """,
        (paper_attempt_id,),
    )
