"""Practice question attempts repository.

Manages practice_question_attempts table for standalone question practice.
Separate from paper workflow - students practice individual questions.

Design:
- Each practice attempt has UUID (generated by caller)
- Links to question_submissions (student work)
- Soft delete via deleted_at timestamp
- Separate context from paper attempts (enforced by submission_contexts)

Usage:
    from paperlab.data.repositories.marking import practice
    from paperlab.data.database import connection

    with connection() as conn:
        attempts = practice.get_attempts_for_student(student_id=1, conn=conn)
        practice.soft_delete_attempt(attempt_id=1, deleted_by=1, conn=conn)
        conn.commit()
"""

from sqlite3 import Connection
from typing import Any

from paperlab.config.constants import Tables


def get_attempts_for_student(student_id: int, conn: Connection) -> list[dict[str, Any]]:
    """Get all practice question attempts for student with question details.

    Returns attempts with question display names from joined tables.
    Excludes soft-deleted attempts (deleted_at IS NULL).
    Orders by most recent first.

    Args:
        student_id: Student ID
        conn: Database connection

    Returns:
        List of dicts with keys:
        - id: int
        - attempt_uuid: str
        - question_display: str (e.g., "Q13 Nov 2023")
        - paper_name: str (from exam_types.display_name)
        - exam_date: str (from papers.exam_date)
        - created_at: datetime
        - submitted_at: datetime | None (from question_submissions)
        - completed_at: datetime | None (from marking_attempts)
        - marks_awarded: int | None (sum of marks, only for completed)
        - marks_available: int | None (total marks, only for completed)

    Example:
        >>> attempts = get_attempts_for_student(1, conn)
        >>> attempts[0]["question_display"]
        "Q13 Nov 2023"
    """
    cursor = conn.execute(
        f"""
        SELECT
            pqa.id,
            pqa.attempt_uuid,
            'Q' || q.question_number as question_display,
            COALESCE(et.display_name, p.exam_identifier) as paper_name,
            p.exam_date,
            pqa.created_at,
            qs.submitted_at,
            ma.attempted_at as completed_at,
            SUM(qmr.marks_awarded) as marks_awarded,
            SUM(mc.marks_available) as marks_available
        FROM {Tables.PRACTICE_QUESTION_ATTEMPTS} pqa
        JOIN {Tables.QUESTION_SUBMISSIONS} qs ON pqa.submission_id = qs.id
        JOIN {Tables.QUESTIONS} q ON qs.question_id = q.id
        JOIN {Tables.PAPERS} p ON q.paper_id = p.id
        LEFT JOIN {Tables.EXAM_TYPES} et ON p.exam_type_id = et.id
        LEFT JOIN {Tables.MARKING_ATTEMPTS} ma ON qs.id = ma.submission_id AND ma.status = 'success'
        LEFT JOIN {Tables.QUESTION_MARKING_RESULTS} qmr ON ma.id = qmr.marking_attempt_id
        LEFT JOIN {Tables.MARK_CRITERIA} mc ON qmr.mark_criteria_id = mc.id
        WHERE pqa.student_id = ?
          AND pqa.deleted_at IS NULL
        GROUP BY pqa.id, pqa.attempt_uuid, q.question_number, paper_name,
                 p.exam_date, pqa.created_at, qs.submitted_at, ma.attempted_at
        ORDER BY pqa.created_at DESC
    """,
        (student_id,),
    )

    columns = [
        "id",
        "attempt_uuid",
        "question_display",
        "paper_name",
        "exam_date",
        "created_at",
        "submitted_at",
        "completed_at",
        "marks_awarded",
        "marks_available",
    ]
    return [dict(zip(columns, row, strict=False)) for row in cursor.fetchall()]


def get_attempt_by_uuid(attempt_uuid: str, conn: Connection) -> dict[str, Any] | None:
    """Get practice attempt by UUID.

    Args:
        attempt_uuid: External UUID
        conn: Database connection

    Returns:
        Dict with practice attempt data if found, None otherwise.
        Keys: id, attempt_uuid, student_id, submission_id, created_at
    """
    cursor = conn.execute(
        f"""
        SELECT id, attempt_uuid, student_id, submission_id, created_at
        FROM {Tables.PRACTICE_QUESTION_ATTEMPTS}
        WHERE attempt_uuid = ? AND deleted_at IS NULL
    """,
        (attempt_uuid,),
    )

    row = cursor.fetchone()
    if row is None:
        return None

    return {
        "id": row[0],
        "attempt_uuid": row[1],
        "student_id": row[2],
        "submission_id": row[3],
        "created_at": row[4],
    }


def get_attempt(attempt_id: int, conn: Connection) -> dict[str, Any]:
    """Get practice question attempt by ID.

    Args:
        attempt_id: Practice attempt ID
        conn: Database connection

    Returns:
        Dict with id, attempt_uuid, student_id, submission_id, created_at

    Raises:
        ValueError: If attempt not found or deleted
    """
    cursor = conn.execute(
        f"""
        SELECT id, attempt_uuid, student_id, submission_id, created_at
        FROM {Tables.PRACTICE_QUESTION_ATTEMPTS}
        WHERE id = ? AND deleted_at IS NULL
        """,
        (attempt_id,),
    )

    row = cursor.fetchone()
    if row is None:
        raise ValueError(f"Practice attempt {attempt_id} not found")

    return {
        "id": row[0],
        "attempt_uuid": row[1],
        "student_id": row[2],
        "submission_id": row[3],
        "created_at": row[4],
    }


def soft_delete_attempt(
    attempt_id: int,
    deleted_by: int,
    conn: Connection,
) -> None:
    """Soft delete practice question attempt.

    Sets deleted_at timestamp. Preserves data for audit trail.

    Args:
        attempt_id: Practice question attempt ID
        deleted_by: Student ID who deleted it
        conn: Database connection

    Raises:
        ValueError: If attempt doesn't exist or already deleted
    """
    # Check if exists and not already deleted
    cursor = conn.execute(
        f"SELECT id FROM {Tables.PRACTICE_QUESTION_ATTEMPTS} "
        f"WHERE id = ? AND deleted_at IS NULL",
        (attempt_id,),
    )
    if cursor.fetchone() is None:
        raise ValueError(f"Practice attempt {attempt_id} not found or already deleted")

    # Soft delete
    conn.execute(
        f"""
        UPDATE {Tables.PRACTICE_QUESTION_ATTEMPTS}
        SET deleted_at = CURRENT_TIMESTAMP,
            deleted_by = ?
        WHERE id = ?
        """,
        (deleted_by, attempt_id),
    )


def restore_attempt(
    attempt_id: int,
    restored_by: int,
    conn: Connection,
) -> None:
    """Restore soft-deleted practice question attempt.

    Clears deleted_at timestamp to make attempt visible again.
    Used for undo functionality after accidental delete.

    Args:
        attempt_id: Practice question attempt ID to restore
        restored_by: Student ID who is restoring it
        conn: Database connection

    Raises:
        ValueError: If attempt doesn't exist, not deleted, or not owned by student
    """
    # Check if exists and is deleted, and owned by the student
    cursor = conn.execute(
        f"""
        SELECT id, student_id FROM {Tables.PRACTICE_QUESTION_ATTEMPTS}
        WHERE id = ? AND deleted_at IS NOT NULL
        """,
        (attempt_id,),
    )
    row = cursor.fetchone()
    if row is None:
        raise ValueError(f"Practice attempt {attempt_id} not found or not deleted")

    if row[1] != restored_by:
        raise ValueError(f"Practice attempt {attempt_id} not owned by student {restored_by}")

    # Restore (clear deleted_at and deleted_by)
    conn.execute(
        f"""
        UPDATE {Tables.PRACTICE_QUESTION_ATTEMPTS}
        SET deleted_at = NULL,
            deleted_by = NULL
        WHERE id = ?
        """,
        (attempt_id,),
    )
