"""API models for attempt endpoints (Flow 2).

Request/response models for paper attempts, practice attempts, and discovery.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# --- Paper Attempt Models ---


class CreatePaperAttemptRequest(BaseModel):
    """Request to create draft paper attempt."""

    attempt_uuid: str = Field(..., description="UUID v4, generated by client")
    exam_board: str = Field(..., description="e.g., 'pearson-edexcel'")
    exam_level: str = Field(..., description="e.g., 'gcse'")
    subject: str = Field(..., description="e.g., 'mathematics'")
    paper_code: str = Field(..., description="e.g., '1MA1/3H'")
    year: int = Field(..., description="e.g., 2023")
    month: int = Field(..., ge=1, le=12, description="Month (1-12)")

    model_config = ConfigDict(populate_by_name=True)


class CreatePaperAttemptResponse(BaseModel):
    """Response after creating paper attempt."""

    id: int
    attempt_uuid: str
    paper_name: str
    exam_date: str
    created_at: datetime
    submitted_at: datetime | None
    completed_at: datetime | None

    @classmethod
    def from_domain(cls, data: dict[str, Any]) -> "CreatePaperAttemptResponse":
        """Create response from domain dict.

        Args:
            data: Dict containing:
                - id: int
                - attempt_uuid: str
                - paper_name: str
                - exam_date: str
                - created_at: datetime
                - submitted_at: datetime | None
                - completed_at: datetime | None

        Returns:
            CreatePaperAttemptResponse
        """
        return cls(
            id=data["id"],
            attempt_uuid=data["attempt_uuid"],
            paper_name=data["paper_name"],
            exam_date=data["exam_date"],
            created_at=data["created_at"],
            submitted_at=data.get("submitted_at"),
            completed_at=data.get("completed_at"),
        )


class SubmitPaperQuestionRequest(BaseModel):
    """Request to submit one question to a paper attempt."""

    question_number: int
    staging_keys: list[str] = Field(..., description="One or more images for this question")

    model_config = ConfigDict(populate_by_name=True)


class PaperQuestionResponse(BaseModel):
    """Response after submitting a question to paper attempt."""

    question_attempt_id: int
    submission_id: int
    question_number: int


class SubmitResponse(BaseModel):
    """Response after finalizing paper attempt."""

    attempt_id: int
    submitted_at: datetime


class PaperDraftDetailsResponse(BaseModel):
    """Response with draft details for resuming paper upload."""

    id: int
    attempt_uuid: str
    paper_name: str
    exam_date: str
    question_count: int
    submitted_questions: dict[int, int] = Field(
        ..., description="Map of question_number → image_count"
    )

    @classmethod
    def from_domain(
        cls,
        attempt_data: dict[str, Any],
        question_count: int,
        submitted_questions: dict[int, int],
    ) -> "PaperDraftDetailsResponse":
        """Create response from domain data.

        Args:
            attempt_data: Dict containing id, attempt_uuid, paper_name, exam_date
            question_count: Total questions in paper
            submitted_questions: Map of question_number → image_count

        Returns:
            PaperDraftDetailsResponse
        """
        return cls(
            id=attempt_data["id"],
            attempt_uuid=attempt_data["attempt_uuid"],
            paper_name=attempt_data["paper_name"],
            exam_date=attempt_data["exam_date"],
            question_count=question_count,
            submitted_questions=submitted_questions,
        )


# --- Practice Attempt Models (Single-Phase) ---


class CreateAndSubmitPracticeRequest(BaseModel):
    """Request to create AND submit practice attempt in single call.

    Single-phase: creates submission, images, practice attempt, and marks immediately.
    No draft state for practice questions.
    """

    attempt_uuid: str = Field(..., description="UUID v4, generated by client")
    question_id: int = Field(..., description="Database ID of question to practice")
    staging_keys: list[str] = Field(..., description="Already uploaded to staging bucket")

    model_config = ConfigDict(populate_by_name=True)


class PracticeAttemptResponse(BaseModel):
    """Response after creating and submitting practice attempt."""

    id: int
    attempt_uuid: str
    submission_id: int
    question_display: str
    created_at: datetime
    marking_status: str = Field(..., description="'success' or error status")


# --- Discovery Models ---


class PaperMetadata(BaseModel):
    """Paper metadata for discovery endpoint."""

    paper_id: int
    exam_board: str
    exam_level: str
    subject: str
    paper_code: str
    display_name: str
    year: int
    month: int
    total_marks: int
    question_count: int

    @classmethod
    def from_domain(cls, paper: dict[str, Any]) -> "PaperMetadata":
        """Convert domain dict to API response."""
        return cls(
            paper_id=paper["paper_id"],
            exam_board=paper["exam_board"],
            exam_level=paper["exam_level"],
            subject=paper["subject"],
            paper_code=paper["paper_code"],
            display_name=paper["display_name"],
            year=paper["year"],
            month=paper["month"],
            total_marks=paper["total_marks"],
            question_count=paper["question_count"],
        )


class PaperListResponse(BaseModel):
    """Response for GET /api/papers."""

    papers: list[PaperMetadata]


class QuestionMetadata(BaseModel):
    """Question metadata for discovery endpoint."""

    question_id: int
    paper_id: int
    paper_name: str
    exam_date: str  # ISO 8601 format (YYYY-MM-DD) - required by Flutter DateTime.parse()
    question_number: int
    total_marks: int

    @classmethod
    def from_domain(cls, question: dict[str, Any]) -> "QuestionMetadata":
        """Convert domain dict to API response."""
        return cls(
            question_id=question["question_id"],
            paper_id=question["paper_id"],
            paper_name=question["paper_name"],
            exam_date=question["exam_date"],
            question_number=question["question_number"],
            total_marks=question["total_marks"],
        )


class QuestionListResponse(BaseModel):
    """Response for GET /api/questions."""

    questions: list[QuestionMetadata]
