"""Practice question attempts repository.

This repository manages the practice_question_attempts table, which links
individual question submissions to the practice context (as opposed to paper context).

Design:
- Each submission belongs to exactly ONE context (practice OR paper)
- UNIQUE constraint on submission_id enforces single-context rule within practice
- Cross-context validation prevents submissions from appearing in both contexts
- Student controls lifecycle (soft delete via deleted_at timestamp)

Usage:
    from paperlab.data.repositories import practice
    from paperlab.data.database import connection

    with connection() as conn:
        attempt_id = practice.create_practice_attempt(
            attempt_uuid=str(uuid.uuid4()),
            student_id=1,
            submission_id=42,
            conn=conn
        )
        conn.commit()
"""

from sqlite3 import Connection

from paperlab.config.constants import Tables
from paperlab.data.repositories.marking import submission_contexts


def create_practice_attempt(
    attempt_uuid: str,
    student_id: int,
    submission_id: int,
    conn: Connection,
) -> int:
    """Link submission to practice question attempt.

    Args:
        attempt_uuid: UUID for this practice attempt (generated by caller)
        student_id: Student who created the submission
        submission_id: Submission to link (from Pipeline 1)
        conn: Database connection

    Returns:
        Practice attempt ID

    Raises:
        ValueError: If submission already linked to any context (cross-context)
        sqlite3.IntegrityError: If submission_id already linked within practice context

    Note:
        UUID is generated by caller (CLI or frontend), not repository.
        This enables idempotent operations and frontend control.
        M4: CLI generates UUID in command layer
        M5: Frontend generates UUID before API call
    """
    # CRITICAL: Validate submission not in any context (practice OR paper)
    # Prevents cross-context contamination via centralized validation module
    submission_contexts.validate_submission_unlinked(submission_id, conn)

    # Insert practice attempt (UNIQUE constraint prevents duplicates within practice)
    cursor = conn.execute(
        f"""
        INSERT INTO {Tables.PRACTICE_QUESTION_ATTEMPTS}
        (attempt_uuid, student_id, submission_id)
        VALUES (?, ?, ?)
    """,
        (attempt_uuid, student_id, submission_id),
    )

    attempt_id = cursor.lastrowid
    if attempt_id is None:
        raise ValueError("Failed to get practice_attempt_id after INSERT")

    # Do NOT commit here - caller controls transaction
    return attempt_id
