"""Data models for submission pipeline."""

import uuid
from dataclasses import dataclass
from pathlib import Path


@dataclass
class SubmissionRequest:
    """Request to create a submission.

    Contains all information needed to create a submission record
    and store associated images.

    Fields:
        submission_uuid: UUID for this submission (generated by caller)
        student_id: Database ID of student submitting work
        question_id: Database ID of question being submitted
        image_paths: Paths to images of student's work (minimum 1 required)

    Note:
        Every submission MUST have at least one image. The current system
        architecture requires image-based submissions.

        The submission_uuid is generated by the caller (CLI or frontend),
        not by the submission creator. This enables idempotent operations
        and predictable resource naming (e.g., R2 image paths).
    """

    submission_uuid: str
    student_id: int
    question_id: int
    image_paths: list[Path]

    def __post_init__(self) -> None:
        """Validate request after initialization."""
        # Validate UUID format
        try:
            uuid_obj = uuid.UUID(self.submission_uuid, version=4)
            if str(uuid_obj) != self.submission_uuid:
                raise ValueError(f"Invalid UUID format: {self.submission_uuid}")
        except (ValueError, AttributeError) as e:
            raise ValueError(f"Invalid submission UUID: {self.submission_uuid}") from e

        if not isinstance(self.image_paths, list):
            type_name = type(self.image_paths).__name__
            raise TypeError(f"image_paths must be a list, got {type_name}")

        if not self.image_paths:
            raise ValueError("At least one image is required for submission")
